target 'iosApp' do
  use_frameworks!
  platform :ios, '15.6'
  pod 'presentation', :path => '../presentation'
  
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.13.1'
  
  pod 'FirebaseAnalytics'
  pod 'FirebaseDatabase'
  pod 'FirebaseRemoteConfig'
  pod 'Firebase/Crashlytics'
  
  pod 'Reachability', '~> 3.2'
  pod 'FreshchatSDK'
  pod 'UXCam'
  pod 'InputMask', '~> 7.3.0'
  
  pod "ExponeaSDK", "~> 2.18.0"
  pod 'AppsFlyerFramework'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
               end
          end
   end
end
